# clone:
#   git:
#     image: woodpeckerci/plugin-git
#     settings:
#       recursive: true
#       submodule_update_remote: true
pipeline:
  prepare_repo:
    image: alpine:3
    commands:
      - apk add git
        #- git fetch --tags
      - git submodule init
      - git submodule update --recursive --remote

  check_formatting:
    image: tmknom/prettier
    commands:
      - prettier -c src

  check_typos:
    image: alpine:3
    commands:
      - wget -O typos.tar.gz https://github.com/crate-ci/typos/releases/download/v1.14.12/typos-v1.14.12-x86_64-unknown-linux-musl.tar.gz
      - tar -xzf typos.tar.gz
      - ./typos src

  check_documentation_build:
    image: alpine:3
    commands:
      - apk add bash curl git
      - wget -O mdbook.tar.gz https://github.com/rust-lang/mdBook/releases/download/v0.4.30/mdbook-v0.4.30-x86_64-unknown-linux-musl.tar.gz
      - tar -xzf mdbook.tar.gz
      - ls -la mdbook
      - ./update-includes.sh
      - ./mdbook build .

  dead_links:
    image: becheran/mlc:latest
    commands:
      - mlc src/en --offline --ignore-links "*localhost*" --ignore-links "*127.0.0.1*" --ignore-links /api
