steps:
  prepare_repo:
    image: alpine:3
    commands:
      - apk add git
      - git submodule init
      - git submodule update --recursive --remote
    when:
      - event: pull_request

  check_formatting:
    image: tmknom/prettier
    commands:
      - prettier -c src
    when:
      - event: pull_request

  check_typos:
    image: alpine:3
    commands:
      - wget -O typos.tar.gz https://github.com/crate-ci/typos/releases/download/v1.14.12/typos-v1.14.12-x86_64-unknown-linux-musl.tar.gz
      - tar -xzf typos.tar.gz
      - ./typos src
    when:
      - event: pull_request

  check_documentation_build:
    image: alpine:3
    commands:
      - apk add bash curl git
      - wget -O mdbook.tar.gz https://github.com/rust-lang/mdBook/releases/download/v0.4.30/mdbook-v0.4.30-x86_64-unknown-linux-musl.tar.gz
      - tar -xzf mdbook.tar.gz
      - ls -la mdbook
      - ./update-includes.sh
      - ./mdbook build .
    when:
      - event: pull_request

  dead_links:
    image: becheran/mlc:latest
    commands:
      - mlc src/en --offline --ignore-links "*localhost*" --ignore-links "*127.0.0.1*" --ignore-links /api
    when:
      - event: pull_request
