# clone:
#   git:
#     image: woodpeckerci/plugin-git
#     settings:
#       recursive: true
#       submodule_update_remote: true
pipeline:
  prepare_repo:
    image: alpine:3
    commands:
      - apk add git
        #- git fetch --tags
      - git submodule init
      - git submodule update --recursive --remote

  check_formatting:
    image: tmknom/prettier
    commands:
      - prettier -c src

  check_typos:
    image: apline:3
    commands:
      - curl -o typos.tar.gz https://github.com/crate-ci/typos/releases/download/v1.14.12/typos-v1.14.12-x86_64-unknown-linux-musl.tar.gz
      - tar -xzf typos.tar.gz
      - ./typos src/en

  check_documentation_build:
    image: rust:1.61-slim-buster
    commands:
      - cargo install mdbook --git https://github.com/Ruin0x11/mdBook.git --branch localization
            --rev 9d8147c --force --debug
      - apt-get update
      - apt-get install git curl -y
      - ./update-includes.sh
      - mdbook build .

  dead_links:
    image: becheran/mlc:latest
    commands:
      - mlc src/en --offline --ignore-links "*localhost*" --ignore-links "*127.0.0.1*" --ignore-links /api
